name: Build LaTeX and Commit PDF

on:
  push:
    branches: [ build-test ]
    paths-ignore:
      - 'Rules.pdf'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: Rules.tex

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: pdf
          path: Rules.pdf